import Head from 'next/head'
import Link from 'next/link'
import { Wrap, WrapItem, Heading, SimpleGrid, Box, Center } from "@chakra-ui/react"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SimpleGrid columns={2} spacing={10}>
        <Link href='/posts'>
          <a>
            <Box p={10} shadow="md" borderWidth="1px" flex="1" borderRadius="md" fontWeight='700'>
              <Center>Posts</Center>
            </Box>
          </a>
        </Link>
        <Link href='/users'>
          <a>
            <Box p={10} shadow="md" borderWidth="1px" flex="1" borderRadius="md" fontWeight='700'>
              <Center>Users</Center>
            </Box>
          </a>
        </Link>
      </SimpleGrid>
    </>
  )
}
